Chat bff refactors
onecx-apps/onecx-chat-bff pull request #2
Opened 2024-12-16 08:50 UTC by BenjaminPabst

2024-12-17 11:01 UTC, andrejpetras commented on src/main/helm/values.yaml
> +              defaultClientScopes: [ ocx-ch:all, ocx-me:all, ocx-pa:all, ocx-pm:read ]
Why does the client need all these scopes (except ocx-pm)? Which applications need these scopes? ocx-ch, ocx-me, ocx-pa?

2024-12-17 11:01 UTC, andrejpetras commented on README.md
> +If you want to build an _über-jar_, execute the following command:
We are not using uber-jar, this could be removed

2024-12-17 11:01 UTC, andrejpetras commented on pom.xml
> +  <version>1.0.0-SNAPSHOT</version>
<version>999-SNAPSHOT</version>

2024-12-17 11:01 UTC, andrejpetras commented on pom.xml
> +              <typeMappings>File=byte[]</typeMappings>
Do we have images/data in the OpenAPI definition? If not remove this line

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +    public Response addParticipant(String chatId, @Valid @NotNull AddParticipantDTO addParticipantDTO) {
Remove the `Valid` and `NotNull` annotation. This should be generated in ChatsApiService, otherwise we need to update the OpenAPI definition to have it there.

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +    public Response createChat(@Valid @NotNull CreateChatDTO createChatDTO) {
Remove the `Valid` and `NotNull` annotation.

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(participantMapper.map(p)).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(mapper.map(c)).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(mDto).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +    public Response createChatMessage(String chatId, @Valid @NotNull CreateMessageDTO createMessageDTO) {
Remove the Valid and NotNull annotation.

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            Response r = getChatParticipants(chatId);
Replace `getChatParticipants` with internal method, do not use public method for internal call (to many mapping and mixing calls)

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(dto).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(m2).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(p2).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(resultDTOs).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            return Response.status(200).entity(resultDTO).build();
Replace 200 with Response.Status.OK

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +    public Response searchChats(@Valid @NotNull ChatSearchCriteriaDTO chatSearchCriteriaDTO) {
Remove the Valid and NotNull annotation.

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +    public Response updateChat(String id, @Valid @NotNull UpdateChatDTO updateChatDTO) {
Remove the Valid and NotNull annotation.

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +
Missing constraints mapper

```
    @ServerExceptionMapper
    public RestResponse<ProblemDetailResponseDTO> constraint(ConstraintViolationException ex) {
        return exceptionMapper.constraint(ex);
    }
```
https://github.com/onecx/onecx-theme-bff/blob/main/src/main/java/org/tkit/onecx/themes/bff/rs/controllers/ThemeRestController.java#L133C1-L136C6

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatSocket.java
> +                        System.out.println("Unable to send message: " + result.getException());
Remove system out please use logger. Log stack-trace?

2024-12-17 11:01 UTC, andrejpetras commented on src/main/java/org/tkit/onecx/chat/bff/rs/helper/MessageEncoder.java
> +            mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
Move next two lines to static block

2024-12-17 11:01 UTC, andrejpetras commented on src/main/resources/application.properties
> +quarkus.http.port=8082
Why? please remove this, all application muss run on port 8080 as default port

2024-12-17 11:01 UTC, andrejpetras commented on src/main/resources/application.properties
> +quarkus.http.filter.images.header."Cache-Control"=max-age=432000
Do we have here images? Please remove the filter

2024-12-17 11:01 UTC, andrejpetras commented on src/main/resources/application.properties
> +quarkus.openapi-generator.codegen.spec.onecx_chat_internal_openapi_yaml.base-package=gen.org.tkit.onecx.chat.bff.clients
The package should be without `bff`  -> gen.org.tkit.onecx.chat.clients

2024-12-17 11:01 UTC, andrejpetras commented on src/test/java/org/tkit/onecx/chat/bff/rs/ChatRestControllerTest.java
> +        String result = "{\r\n" +
Rewrite to client DTO model

2024-12-17 11:01 UTC, andrejpetras commented on src/test/java/org/tkit/onecx/chat/bff/rs/ChatRestControllerTest.java
> +        //TODO
Do we need this?

2024-12-17 11:01 UTC, andrejpetras commented on src/main/openapi/openapi-bff.yaml
> +        "400":
GET method and bad request, when?

2024-12-18 10:43 UTC, bbrynski commented on src/main/openapi/openapi-bff.yaml
> +        "400":
I deleted that 400 part

2025-01-15 11:48 UTC, JordenReuter requested changes

2025-01-15 11:48 UTC, JordenReuter commented on src/main/helm/values.yaml
> +              defaultClientScopes: [ ocx-pm:read ]
please add 
ocx-chat:all 
otherwise the bff cant access the svc

2025-01-15 12:06 UTC, JordenReuter requested changes

2025-01-15 12:06 UTC, JordenReuter commented on .dockerignore
> +!target/*-runner
remove this file

2025-01-15 12:06 UTC, JordenReuter commented on .vscode/launch.json
> +// A launch configuration that compiles the extension and then opens it inside a new window
remove .vscode and add it to gitignore

2025-01-15 12:06 UTC, JordenReuter commented on mvnw
> +#!/bin/sh
remove this file

2025-01-15 12:06 UTC, JordenReuter commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
remove this file

2025-01-15 12:06 UTC, JordenReuter commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            ChatPageResult result = response.readEntity(new GenericType<ChatPageResult>() {
why GenericType?

2025-01-15 12:06 UTC, JordenReuter commented on src/main/java/org/tkit/onecx/chat/bff/rs/controllers/ChatRestController.java
> +            ChatPageResult result = response.readEntity(new GenericType<ChatPageResult>() {
why GenericType?

2025-01-15 12:06 UTC, JordenReuter commented on src/main/openapi/openapi-bff.yaml
> +      responses:
whats if no criteria was provided?
add 400 response

2025-01-15 12:06 UTC, JordenReuter commented on src/test/java/org/tkit/onecx/chat/bff/rs/ChatRestControllerTest.java
> +@QuarkusTestResource(MockServerTestResource.class)
Your AbstractTest already has this annotation. remove it

2025-01-24 09:11 UTC, merged